### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by MrrrrFox** [JPETTomography/j-pet-console-fe#11]
### Problem description
Currently the views does not show any icons.

### TO-DOs
- [ ] Add ReactSVG lib
- [ ] Add missing icons (SVG files from [Heroicons](https://heroicons.com/))
- [ ] Prepare custom component for handling the SVGs (wrapper with `shrink-0`)
- [ ] Add missing icons provided by the design to the views
