### ISSUE TITLE
User login & auth

### ISSUE THREAD

**Issue by MrrrrFox** [JPETTomography/j-pet-console-fe#13]
### Problem description
Currently, the form on Login page does nothing.

### TO-DOs
- [x] Add `onSubmit` method to the login form to fetch for user
- [x] Save successfully returned token to cookie / local storage
- [x] Add redirect to ExprimentsList page after successful login
- [ ] Show possible errors
- [x] Add authorization on another pages
