### ISSUE TITLE
Current user logic

### ISSUE THREAD

**Issue by MrrrrFox** [JPETTomography/j-pet-console-fe#14]
### Problem description
Currently the app does not provide any mechanism of user handling. Although FTTB we do not have the fronted & backend synced, we can prepare imitation of the logic as an initial setup for the mechanisms.

### TO-DOs
- General logic
  - [ ] Add inline example of the user (DB imitation)
  - [ ] #13
  - [ ] Save user data to cookie / local storage
  - [ ] Show user data in the header
  - [ ] Add possibiity for user to logout (redirect to homepage & remove user data from cookie / local storage)
  - [ ] Authenticate the user (redirect to homepage on ExperimentList & Experiment view when user is not logged in)
