### ISSUE TITLE
Light/dark mode

### ISSUE THREAD

**Issue by MrrrrFox** [JPETTomography/j-pet-console-fe#3]
### Problem description
Th application should have both light & dark modes in terms of UI.

### TO-DOs
- To design:
  - [ ] Prepare the dark mode design.
- To code:
  - [ ] Generalize the design not to use the colors inline but some sort of primary/secondary... naming so that handling light/dark modes were easier to maintain.
  - [ ] Add light/dark mode switcher.
  - [ ] Add dark mode color scheme.
